### ISSUE TITLE
Cant pick already uploaded video

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-curator#177] opened 2023-05-12 16:13 UTC
Hello, i have field
```
CuratorPicker::make('video')
                ->acceptedFileTypes(['video/*'])
                ->constrained()
                ->required(),
```
i can add new video, but i cant pick existing video

**Comment by awcodes** [comment] 2023-05-15 13:10
Can you provide a reproduction repo? I can't replicate this or I'm not understanding the issue.

**Comment by lotarbo** [comment] 2023-05-15 13:27
@awcodes i make video, hope it can help. If no, i will make repo)


https://github.com/awcodes/filament-curator/assets/1766890/31a60142-046d-4f71-909e-1848a13e8216

**Comment by awcodes** [comment] 2023-05-15 14:58
Ok, this is happening because your accepted file types is too generic. The thumbnails are looking for actual mime types for the video. I.e. when the video is saved it's mime type isn't 'video/*' it's propbably 'video/mp4' so it's getting disabled as a selectable option.

**Comment by lotarbo** [comment] 2023-05-15 15:22
@awcodes so, its not a bug and i must use strict mime type?

**Comment by awcodes** [comment] 2023-05-15 15:31
I'll make a note to look into a way to maybe regex it. But for now you would need to use strict mime types.

Or you're welcome to PR the fix. 😄

**Comment by awcodes** [comment] 2023-07-03 16:27
Resolved with v2.8.0

**Closed as completed by awcodes** 2023-07-03 16:27 UTC
